name: 'ü™Ñ OrderFlux | üîÑ CI'

on:
  push:
    branches:
      - develop
    paths-ignore:
      - README.md
  pull_request:
    branches:
      - develop
      - feature/*
      - fix/*
      - hotfix/*
      - epic/*
      - release/*
    paths-ignore:
      - README.md

  workflow_dispatch:

jobs:
  cleanup:
    name: 'üßπ Clean up GitHub repo'
    runs-on: ubuntu-latest
    permissions: write-all
    if: github.event_name != 'pull_request'

    steps:
      - name: 'üóë Delete workflow runs'
        uses: Mattraks/delete-workflow-runs@v2
        with:
          retain_days: 7
          keep_minimum_runs: 1
          delete_workflow_pattern: ci.yml

  lints:
    name: 'ü™Ñ Lints | ${{ matrix.command.name }}'
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17-alpine3.20
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: testing
          POSTGRES_USER: db
          POSTGRES_PASSWORD: db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    strategy:
      fail-fast: false
      matrix:
        command:
          - {
              name: 'üîç PHPStan',
              command: './vendor/bin/phpstan analyse --no-progress --error-format=github --memory-limit=2G',
              php: true,
            }
          - {
              name: 'üßΩ Laravel Pint',
              command: './vendor/bin/pint --test --cache-file=var/cache/pint/pint.cache --ansi --format=checkstyle | cs2pr',
              php: true,
            }
          - {
              name: 'üè† Rector',
              command: './vendor/bin/rector process --dry-run --no-progress-bar --output-format=github --ansi',
              php: true,
            }

    steps:
      - name: 'üõé Checkout'
        uses: actions/checkout@v5

      - name: '‚öôÔ∏è Prepare environment'
        uses: ./.github/actions/setup-environment
        with:
          use-php: ${{ matrix.command.php }}

      - name: ${{ matrix.command.name }}
        run: ${{ matrix.command.command }}
        env:
          DB_HOST: 127.0.0.1
          DB_DATABASE: testing
          DB_USERNAME: db
          DB_PASSWORD: db

  tests:
    name: '‚ôªÔ∏è Tests | ${{ matrix.command.name }}'
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17-alpine3.20
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: testing
          POSTGRES_USER: db
          POSTGRES_PASSWORD: db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    strategy:
      fail-fast: false
      matrix:
        command:
          - { name: 'üî¨ Unit',     command: 'php artisan test --parallel', report: false }
          - { name: '‚òÇÔ∏è Coverage', command: 'php artisan test --coverage --compact --coverage-clover coverage/coverage-clover.xml', report: true  }

    steps:
      - name: 'üõé Checkout'
        uses: actions/checkout@v5

      - name: '‚öôÔ∏è Prepare environment'
        uses: ./.github/actions/setup-environment
        with:
          use-php: true

      - name: 'üóÑÔ∏è Grant CREATEDB permission'
        run: PGPASSWORD=db psql -h 127.0.0.1 -U db -d testing -c "ALTER USER db CREATEDB;"

      - name: '${{ matrix.command.name }} tests'
        run: ${{ matrix.command.command }}
        env:
          DB_HOST: 127.0.0.1
          DB_DATABASE: testing
          DB_USERNAME: db
          DB_PASSWORD: db

      - name: '‚òÇÔ∏è Upload results to Codecov'
        if: ${{ !cancelled() && matrix.command.report }}
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: OrderFlux/order-flux-webapp
          flags: ${{ matrix.command.name }}
          directory: ./coverage
          files: ./coverage/coverage-clover.xml
          verbose: true
          name: codecov-report
          commit_parent: ${{ github.event.pull_request.base.sha }}

      - name: '‚òÇÔ∏è Upload test results to Codecov'
        if: ${{ !cancelled() && matrix.command.report }}
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: ${{ matrix.command.name }}
          directory: ./coverage
          report_type: test_results
          fail_ci_if_error: true
